#spring:
#  application:
#    name: demo1
##  cloud:
##    config:
##      uri: http://spring-cloud-config-server:8888
#  profiles:
#    active: dev
#  data:
#    mongodb:
#      database: demo2
##      host: localhost
#      host: db
#      port: 27017
## for creation of correlation id and zipkin request tracing by correlation id
##  sleuth:
##    sampler:
##      probability: 1.0
##  zipkin:
##    base-url: http://localhost:9411/
## -----------------------------------------------------------
#server:
#  port: 8081
#logging:
#  file: demo1.log
##eureka:
##  client:
##    service-url:
##      defaultZone: http://eureka:8761/eureka/
spring:
  thymeleaf:
    prefix: /WEB-INF/html/
    suffix: .html
    mode: HTML5